### ISSUE TITLE
Maybe a small bug here.

### ISSUE THREAD

**Issue by huixiancheng** [GangZhang842/SMVF#2]
In infer stage just return one value.
https://github.com/GangZhang842/SMVF/blob/22ed741b057f5ed3d465389dd81545b89ca6171c/evaluate.py#L34-L39
https://github.com/GangZhang842/SMVF/blob/22ed741b057f5ed3d465389dd81545b89ca6171c/models/mvf_vfe.py#L166-L176
So here shou be:
~~~
pred_cls = model.infer(pcds_xyzi.squeeze(0).cuda(), pcds_coord.squeeze(0).cuda(), pcds_sphere_coord.squeeze(0).cuda())
~~~

**Comment by GangZhang842** [comment]
@huixiancheng okay. It`s an abvious fault. Thank you
